### ISSUE TITLE
Inject social auth credentials

### ISSUE THREAD

**Issue by msteiger** [beevelop/docker-weblate#11]
This image works great out of the box - thanks for building it! I've set it up with GitHub OAuth, but this requires installing an editor such as `vim` and manually editing the `settings.py` file. Due to the container nature, these changes are lost as soon as I change the `docker-compose.yml` file and a new container is set up from the image.

Would it be feasible to inject the `SOCIAL_AUTH_*` tokens somehow? How would that work? Mount the entire `settings.py` or use environment variables?

**Comment by msteiger** [comment]
It would be great if that could be integrated in the Weblate 2.6 Dockerfile. Again, I'd be happy to assist.

**Comment by beevelop** [comment]
Thank you for your feedback. I added a new branch which makes use of the `SOCIAL_AUTH_*` ENVs. Would you mind testing `beevelop/weblate:feat-social-auth` (available from Docker Hub) for your use case?

**Comment by msteiger** [comment]
I built it from source and it seems to work: http://139.59.140.109:8000. Google just fails because the source hostname differs.

The facebook login shows up, because the FB plugin is always enabled even though FB credentials are not configured.

One possibility would be to inject the enabled flag from env as well, another would be to check whether the credentials are non-empty (maybe a better one) and a third option would be to mount the entire `settings.py` file from the host. This would be the most comprehensive one.

**Comment by beevelop** [comment]
Thank you. I made a few changes to the feature branch to dynamically enable the available authentication backends.

Mounting the `settings.py` is always possible for customisation. It's just not documented as I'd like to make everything configurable through ENVs. Just mount `/usr/local/lib/python2.7/dist-packages/weblate/settings.py` to your host system.

**Comment by msteiger** [comment]
Works for me. Fixed by 68fd9145ef7dfae3d4804192dfbb6f41ff57709f.

![image](https://cloud.githubusercontent.com/assets/1820007/14990101/548730a4-115b-11e6-97dd-fadefe2053ec.png)

Google and FB icons are not showing, but that is a different issue.

**Comment by beevelop** [comment]
Alright, thank you. I will merge the changes into master.

**Comment by msteiger** [comment]
Thank you for adding this functionality.
