### ISSUE TITLE
Can't connect

### ISSUE THREAD

**Issue by oeroche** [beevelop/docker-weblate#16]
I managed to run weblate with manual setup, but I face two issues:
1. I can't connect with the default admin credentials with the email provided in WEBLATE_ADMIN_EMAIL and the Un1c0rn password described in doc
2. I don't receive any activation email when I try to sign in a new user...

So far I can't do anything with weblate :-(

**Comment by beevelop** [comment]
@Winangel By running the commands as stated in the `README` you can login with Username `admin` and Password `Un1c0rn`

**Comment by oeroche** [comment]
Thanks for your answer!

I jumped to the Manually paragraph and didn't see this line. Sorry for that.
