### ISSUE TITLE
Support for GitLab OAuth

### ISSUE THREAD

**Issue by buffcode** [beevelop/docker-weblate#42]
`settings.py` is missing imports for the social auth environment variables for GitLab. As such, the backend cannot be enabled.

What seems to be missing from the docs is the possibility to define a hosted instance of GitLab (eg, `gitlab.company.com`).

Docs: https://docs.weblate.org/en/latest/admin/auth.html#gitlab-oauth2

**Comment by beevelop** [comment]
@buffcode Thank you for the proposal. I put together the required chances and will merge them with the next release. Are able to verify it's working by any chance?
